// moment output types
const DAY = 'day';
const HOURS = 'hours';
const MINUTES = 'minutes';

// wages
const NORMAL_WAGE = 4.25;
const EVENING_WAGE = 5.5;
const LOW_OVERTIME_MULTIPLIER = 1.25;
const MEDIUM_OVERTIME_MULTIPLIER = 1.5;
const HIGH_OVERTIME_MULTIPLIER = 2;

module.exports = {
  DAY,
  HOURS,
  MINUTES,
  NORMAL_WAGE,
  EVENING_WAGE,
  LOW_OVERTIME_MULTIPLIER,
  MEDIUM_OVERTIME_MULTIPLIER,
  HIGH_OVERTIME_MULTIPLIER
};
